# import = ["/Users/lotaher/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/rose-pine.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/xterm.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/base16_default_dark.toml"]

[colors.primary]
background = "#121212"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#dfaf87"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"

[shell]
program = "/bin/bash"
args = ["--login"]

[window]
title = "Terminal"
dynamic_title = true
# decorations = "none"
# opacity = 0.95

[font]
size = 20
    [font.normal]
    family = "GeistMono Nerd Font"
    # family = "Consolas NF"
    # style = "Medium"
    # family = "BigBlueTerm437 Nerd Font"


[window.padding]
x = 7
y = 7

[scrolling]
history = 100000
