import = ["/Users/lotaher/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/xterm.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/base16_default_dark.toml"]

[shell]
program = "/bin/bash"
args = ["--login"]

[window]
title = "Terminal"
dynamic_title = true
# decorations = "none"
# opacity = 0.95

[font]
size = 18
    [font.normal]
    family = "GeistMono Nerd Font"
    style = "Medium"



[window.padding]
x = 7
y = 7

[scrolling]
history = 100000

# ==== BEGIN CUSTOM THEME ====
# [colors]
#   # Default colors
#   [colors.primary]
#     background = "0x1d2021"
#     foreground = "0xd5c4a1"
#
#   [colors.cursor]
#     text = "0x1d2021"
#     cursor = "0xd5c4a1"
#
#   # Normal colors
#   [colors.normal]
#     black = "0x1d2021"
#     red = "0xfb4934"
#     green = "0xb8bb26"
#     yellow = "0xfabd2f"
#     blue = "0x83a598"
#     magenta = "0xd3869b"
#     cyan = "0x8ec07c"
#     white = "0xd5c4a1"
#
#   # Bright colors
#   [colors.bright]
#     black = "0x665c54"
#     red = "0xfe8019"
#     green = "0x3c3836"
#     yellow = "0x504945"
#     blue = "0xbdae93"
#     magenta = "0xebdbb2"
#     cyan = "0xd65d0e"
#     white = "0xfbf1c7"
# ==== END CUSTOM THEME ====
