[colors]

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.cursor]
text = "#282828"
cursor = "#928374"

[colors.selection]
text = "#928374"
background = "#ebdbb2"

[colors.normal]
black = "#665c54"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#7c6f64"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#bdae93"

[shell]
program = "/bin/bash"
args = ["--login"]

[window]
title = "Terminal"
dynamic_title = true
# decorations = "none"
# opacity = 0.95

[font]
size = 20
    [font.normal]
    family = "Iosevka"
    [font.italic]
    family = "Iosevka"
    [font.bold]
    family = "Iosevka"

[window.padding]
x = 7
y = 7

[scrolling]
history = 100000
