import = ["/Users/lotaher/.config/alacritty/themes/themes/gruvbox_dark.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/rose-pine.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/xterm.toml"]
# import = ["/Users/lotaher/.config/alacritty/themes/themes/base16_default_dark.toml"]

[shell]
program = "/bin/bash"
args = ["--login"]

[window]
title = "Terminal"
dynamic_title = true
# decorations = "none"
# opacity = 0.95

[font]
size = 20
    [font.normal]
    # family = "GeistMono Nerd Font"
    family = "Consolas NF"
    # style = "Medium"
    # family = "BigBlueTerm437 Nerd Font"


[window.padding]
x = 7
y = 7

[scrolling]
history = 100000
